---
title: "Project_3"
author: "Michael Robinson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(ggplot2)
library(dplyr)
library(gridExtra)


data <- read.csv("~/Data_607/Valued_skill_data.csv")
head(data)

plot1 <- ggplot(data, aes(x = Skills.Required.by.Employers, y = Share)) +
   geom_bar(stat = "identity", fill = "skyblue") +
   labs(title = "Employer Skill Distribution", x = "Skill", y = "Percentage") +
       theme(axis.text.x = element_text(angle = 45, hjust = 1))

plot2 <- ggplot(data, aes(x = Skills.Listed.by.Employees, y = Share.1)) +
   geom_bar(stat = "identity", fill = "green") +
   labs(title = "Employee Skill Distribution", x = "Skill", y = "Percentage") +
       theme(axis.text.x = element_text(angle = 45, hjust = 1))

grid.arrange(plot1, plot2, ncol = 2)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
